feature(documentation): updated readme file
idrinth-api-bench/documentation-website pull request #16
Opened 2024-05-19 21:04 UTC by IagoMota

# The Pull Request is ready

- [ ] fixes  idrinth-api-bench/issues#1071
- [ ] all actions are passing
- [ ] only fixes a single issue

## Overview

Made it more noob friendly.

## Documentation-Website

- [ ] mobile view is usable
- [ ] desktop view is usable
- [ ] no a-tags are used directly (NavLink, MailLink, ExternalLink instead)
- [ ] all new texts are added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] shared code has been extracted in a different file

2024-05-20 04:21 UTC, itsmacr8 requested changes
Consider making the change.

2024-05-20 04:21 UTC, itsmacr8 commented on README.md
> +If you encounter any problems with this, try checking the `Token tutorial` right above this section.
I think we can make it a link for easier access instead of instructing to scroll. Syntax `[Token tutorial](link)`

2024-05-20 04:26 UTC, Idrinth requested changes
Please add some line breaks at <= 80 characters to your texts, this would fail the markdown standard lint test if that was active

2024-05-24 18:30 UTC, IagoMota commented on README.md
> +If you encounter any problems with this, try checking the `Token tutorial` right above this section.
Agreed!

2024-05-24 18:47 UTC, IagoMota commented
> Please add some line breaks at <= 80 characters to your texts, this would fail the markdown standard lint test if that was active

Done

2024-05-24 20:12 UTC, IagoMota reviewed
@Idrinth should be okay now

2024-05-25 06:02 UTC, merged